#ifndef COMMAND_H
#define COMMAND_H

enum Command {
    HOME,
    CHANGE_CURRENT_SEMESTER,
    CHANGE_PASSWORD,
    VIEW_STUDENT_INFO,
    VIEW_SCHOOL_YEARS,
    VIEW_SEMESTERS,
    VIEW_COURSES,
    VIEW_CLASSES,
    VIEW_STUDENTS_IN_CLASS,
    VIEW_STUDENTS_IN_COURSE,
    VIEW_SCOREBOARD_OF_COURSE,
    VIEW_SCOREBOARD_OF_CLASS,
    VIEW_SCOREBOARD_OF_STUDENT,
    VIEW_COURSES_OF_STUDENT,
    CREATE_SCHOOL_YEAR,
    CREATE_CLASS,
    CREATE_STUDENT,
    CREATE_SEMESTER,
    CREATE_COURSE,
    ADD_STUDENT_TO_COURSE,
    IMPORT_STUDENTS_IN_CLASS,
    IMPORT_STUDENTS_IN_COURSE,
    IMPORT_SCOREBOARD,
    EXPORT_STUDENTS_IN_COURSE,
    UPDATE_COURSE,
    UPDATE_STUDENT_RESULT,
    EXIT
};

void selectPage();

#endif
